# Generated by Django 5.2.11 on 2026-02-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shoppers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('store_id', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stickers_awarded', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stickers.shopper')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='StickerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem')], max_length=10)),
                ('delta', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='stickers.shopper')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stickers.transaction')),
            ],
            options={
                'db_table': 'sticker_ledger',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField()),
                ('name', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.TextField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stickers.transaction')),
            ],
            options={
                'db_table': 'transaction_items',
            },
        ),
    ]
